### ISSUE TITLE
Nip for kind 34567

### ISSUE THREAD

**Issue by heri16** [jinglescode/nostr-password-manager#4]
Where is the NIP for kind 34567 ?

Which nostr relays support this kind and guarantee them not to be pruned?

**Comment by jinglescode** [comment]
NIP is when:

> They should be fully implemented in at least two clients and one relay -- when applicable.

As such, this does not have a NIP right now.

Most or all relay prune based on a time period, the logic are in-place to re-write to relays to keep data fresh. The better solution is to have a dedicated relay for this application.
